### ISSUE TITLE
Text doesn't fit the screen.

### ISSUE THREAD

**Issue by HenriDellal** [alaskalinuxuser/app_critical_velocity#10]
The text is positioned that way so the left part of it is not visible even on hdpi screen. It is an old issue but it wasn't very noticeable before because there were some pictures on the left and it didn't look bad. There is a screen for mdpi. Hdpi looks way better, just a few characters missing.
![screenshot_2017-07-27-17-38-40](https://user-images.githubusercontent.com/29340702/28676123-7fb93cdc-72f2-11e7-917b-62721f064350.png)

**Comment by alaskalinuxuser** [comment]
Fixed with this commit:
https://github.com/alaskalinuxuser/app_critical_velocity/commit/238d3773225d9f6f3f24c045e8b55e5344133b67

Thanks for all your help in working through these issues! You can test it out in version 2.9.
https://github.com/alaskalinuxuser/app_critical_velocity/blob/master/android/criticalvelocity_2_9.apk

It's still a little bit off, depending on the screen size.

**Comment by alaskalinuxuser** [comment]
![smaller_adjusted](https://user-images.githubusercontent.com/19839527/28683390-e0702248-72ac-11e7-99cf-5d6bf425634f.png)
![med_adj](https://user-images.githubusercontent.com/19839527/28683395-e5265dca-72ac-11e7-9c2f-0becbc27851d.png)
![textfixed](https://user-images.githubusercontent.com/19839527/28683406-eb954950-72ac-11e7-9908-095e12501ed7.png)

**Comment by alaskalinuxuser** [comment]
Still a little wonky on very small screens, but I think it's as close as I can get, because I can't scale the text any smaller without making all new text files.

**Comment by HenriDellal** [comment]
That's brilliant! Looking better now.
![screenshot_2017-07-27-21-04-42](https://user-images.githubusercontent.com/29340702/28685119-7d826f70-730f-11e7-81bd-c3437de7aadc.png)
![screenshot_2017-07-27-21-04-12](https://user-images.githubusercontent.com/29340702/28685130-83a19606-730f-11e7-92ad-d3f80eb46a06.png)
