### ISSUE TITLE
Hardcore mode

### ISSUE THREAD

**Issue by HenriDellal** [alaskalinuxuser/app_critical_velocity#2]
What do you think about implementing mode with higher difficulty? So there are only boost powerups and tunnels are being positioned a bit more differently so they make a harder way.

**Comment by alaskalinuxuser** [comment]
Great idea!

I am still learning, and this is my first libGDX game. Originally, there were no power ups, but my testers said the game was too hard, so I slowed it down and added the power ups. I do plan to implement a few other things, and this is one of them.

**Comment by alaskalinuxuser** [comment]
I have figured out how to make tappable buttons and hope to implement this soon.

**Comment by alaskalinuxuser** [comment]
Added 4 levels of difficulty that you can select with this commit:
https://github.com/alaskalinuxuser/app_critical_velocity/commit/6cdc14ce9002096afe7aa2f4d052ee4c116512be

Each level increases the INCREASE of the speed, so the game gets exponentially faster.

The scoring is also adjusted as follows:
Score to win is (25000 + (50 points for each power up you snagged)) * level of difficulty!

This may need some tweaking.

Enjoy!
