### ISSUE TITLE
Make icon square

### ISSUE THREAD

**Issue by HenriDellal** [alaskalinuxuser/app_critical_velocity#7]
For now icon has different width and height. It leads to changing proportions in some launchers (KISS and probably some others). It may be a launcher issue, but the same bug was found in Yalp Store. I'd fix it myself but I can't find proper editor for this task

**Comment by alaskalinuxuser** [comment]
Good point. I will fix this shortly. And test out some strings.

**Comment by alaskalinuxuser** [comment]
Done.
https://github.com/alaskalinuxuser/app_critical_velocity/commit/2d25afed2ee3b91bda12c9475bbce43050415eff
